#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="/opt/birthday"

get_secret() {
  local id="$1"
  aws secretsmanager get-secret-value \
    --secret-id "$id" \
    --query 'SecretString' --output text 2>/dev/null || true
}

TELEGRAM_TOKEN="$(get_secret 'birthday-bot/telegram-token')"
MONGO_URL="$(get_secret 'birthday-bot/mongo-url')"
DUCKDNS_TOKEN="$(get_secret 'birthday-bot/duckdns-token')"

if [[ -z "$TELEGRAM_TOKEN" || -z "$MONGO_URL" ]]; then
  echo "[fetch-secrets] Missing mandatory secrets. TELEGRAM_TOKEN or MONGO_URL empty." >&2
  exit 1
fi

# Домен мы передаем через переменную окружения DOMAIN_NAME (CDK -> UserData -> ENV)
DOMAIN="${DOMAIN_NAME:-}"
if [[ -z "$DOMAIN" ]]; then
  echo "[fetch-secrets] DOMAIN_NAME is empty; Caddy will run but Telegram webhook over HTTPS may fail." >&2
fi

install -d -m 755 "$ROOT"
cat > "$ROOT/.env" <<EOT
# generated by fetch-secrets.sh
TELEGRAM_BOT_TOKEN=${TELEGRAM_TOKEN}
MONGO_URL=${MONGO_URL}
DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
DOMAIN=${DOMAIN}
EOT
